name: peer_programing
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  multiselect_formfield: ^0.1.2
  searchable_dropdown: ^1.1.3
  # flutter_multiselect: 0.0.1
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.5
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  shared_preferences: ^0.5.6+3
  progress_indicators: ^0.1.5
  smooth_star_rating: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "<1.13.0"
  mockito: ^4.1.1
flutter:
  uses-material-design: true
  assets:
    - 'images/avatar-default-icon.png'